docs(aula_1): primeira aula de ciencias do ambiente
Engenharia-de-Software-UFMS/optativas pull request #6
Opened 2023-06-01 03:29 UTC by wagnerUFMS

Primeira aula de ciências do ambiente.

2023-06-03 16:28 UTC, JerffersonJunior requested changes
Divergência no contexto do título da submissão com os arquivos adicionados. Enviar somente os arquivos relacionados ao título [docs(aula_1): primeira aula de ciencias do ambiente] e lançar as outras aulas separadamente.

2023-06-05 00:23 UTC, wagnerUFMS commented
@JerffersonJunior Alteração realizada!

2023-06-05 00:26 UTC, JerffersonJunior approved these changes

2023-06-05 18:40 UTC, rafaelTsu approved these changes

2023-06-05 18:41 UTC, merged